//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimatePresentation.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RibbonExceptionStringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RibbonExceptionStringTable() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UltimatePresentation.Properties.RibbonExceptionStringTable", typeof(RibbonExceptionStringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Element is not a valid KeyTip scope. 的本地化字符串。
        /// </summary>
        internal static string ElementNotKeyTipScope {
            get {
                return ResourceManager.GetString("ElementNotKeyTipScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; can only host a RibbonApplicationMenuItem, RibbonApplicationSplitMenuItem, RibbonGallery or RibbonSeparator. &apos;{1}&apos; is an invalid container. 的本地化字符串。
        /// </summary>
        internal static string InvalidApplicationMenuOrItemContainer {
            get {
                return ResourceManager.GetString("InvalidApplicationMenuOrItemContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; parameter cannot be Infinity for RibbonControlLengthUnitType.Star. 的本地化字符串。
        /// </summary>
        internal static string InvalidCtorParameterNoInfinityForStarSize {
            get {
                return ResourceManager.GetString("InvalidCtorParameterNoInfinityForStarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; parameter cannot be NaN. 的本地化字符串。
        /// </summary>
        internal static string InvalidCtorParameterNoNaN {
            get {
                return ResourceManager.GetString("InvalidCtorParameterNoNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; parameter is not valid. Valid values are RibbonControlLengthUnitType.Auto, RibbonControlLengthUnitType.Pixel, RibbonControlLengthUnitType.Item, or RibbonControlLengthUnitType.Star. 的本地化字符串。
        /// </summary>
        internal static string InvalidCtorParameterUnknownRibbonControlLengthUnitType {
            get {
                return ResourceManager.GetString("InvalidCtorParameterUnknownRibbonControlLengthUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset cannot be infinity or NaN. 的本地化字符串。
        /// </summary>
        internal static string InvalidKeyTipOffset {
            get {
                return ResourceManager.GetString("InvalidKeyTipOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; can only host a RibbonMenuItem, RibbonSplitMenuItem, RibbonGallery or RibbonSeparator. &apos;{1}&apos; is an invalid container. 的本地化字符串。
        /// </summary>
        internal static string InvalidMenuButtonOrItemContainer {
            get {
                return ResourceManager.GetString("InvalidMenuButtonOrItemContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resize parameters out of bounds. 的本地化字符串。
        /// </summary>
        internal static string ResizeParametersNotValid {
            get {
                return ResourceManager.GetString("ResizeParametersNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set both ContextualTabGroupHeadersSource and ContextualTabGroupHeaders. 的本地化字符串。
        /// </summary>
        internal static string Ribbon_ContextualTabHeadersSourceInvalid {
            get {
                return ResourceManager.GetString("Ribbon_ContextualTabHeadersSourceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Add gallery to Quick Access Toolbar 的本地化字符串。
        /// </summary>
        internal static string RibbonContextMenu_AddGalleryToQAT {
            get {
                return ResourceManager.GetString("RibbonContextMenu_AddGalleryToQAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Add to Quick Access Toolbar 的本地化字符串。
        /// </summary>
        internal static string RibbonContextMenu_AddToQAT {
            get {
                return ResourceManager.GetString("RibbonContextMenu_AddToQAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ma_ximize the Ribbon 的本地化字符串。
        /// </summary>
        internal static string RibbonContextMenu_MaximizeTheRibbon {
            get {
                return ResourceManager.GetString("RibbonContextMenu_MaximizeTheRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mi_nimize the Ribbon 的本地化字符串。
        /// </summary>
        internal static string RibbonContextMenu_MinimizeTheRibbon {
            get {
                return ResourceManager.GetString("RibbonContextMenu_MinimizeTheRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Remove from Quick Access Toolbar 的本地化字符串。
        /// </summary>
        internal static string RibbonContextMenu_RemoveFromQAT {
            get {
                return ResourceManager.GetString("RibbonContextMenu_RemoveFromQAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Show Quick Access Toolbar above the Ribbon 的本地化字符串。
        /// </summary>
        internal static string RibbonContextMenu_ShowQATAbove {
            get {
                return ResourceManager.GetString("RibbonContextMenu_ShowQATAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Show Quick Access Toolbar below the Ribbon 的本地化字符串。
        /// </summary>
        internal static string RibbonContextMenu_ShowQATBelow {
            get {
                return ResourceManager.GetString("RibbonContextMenu_ShowQATBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string RibbonGallery_AllFilter {
            get {
                return ResourceManager.GetString("RibbonGallery_AllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RibbonGroupsPanel RegisterStarLayoutProvider and UnregisterStarLayoutProvider accepts only IProvideStarLayoutInfo instances. 的本地化字符串。
        /// </summary>
        internal static string RibbonGroupsPanel_InvalidRegistrationParameter {
            get {
                return ResourceManager.GetString("RibbonGroupsPanel_InvalidRegistrationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More controls 的本地化字符串。
        /// </summary>
        internal static string RibbonQuickAccessToolBar_OverflowButtonToolTip {
            get {
                return ResourceManager.GetString("RibbonQuickAccessToolBar_OverflowButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window must be shown before extending glass 的本地化字符串。
        /// </summary>
        internal static string RibbonWindow_ExtendUnShownGlass {
            get {
                return ResourceManager.GetString("RibbonWindow_ExtendUnShownGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target element cannot receive focus. 的本地化字符串。
        /// </summary>
        internal static string SetFocusFailed {
            get {
                return ResourceManager.GetString("SetFocusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot perform operation. 的本地化字符串。
        /// </summary>
        internal static string UIA_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("UIA_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element does not exist or it is virtualized. 的本地化字符串。
        /// </summary>
        internal static string VirtualizedElement {
            get {
                return ResourceManager.GetString("VirtualizedElement", resourceCulture);
            }
        }
    }
}
